services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"

# Base de Datos 
  mongodb:
    image: mongo:latest
    container_name: mongodb_data
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # API 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_backend
    ports:
      - "8080:80" 
    depends_on:
      - mongodb

volumes:
  mongodb_data:
