server {
    listen 80;
    server_name intranet-knowledge.servehalflife.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name intranet-knowledge.servehalflife.com;

    root /usr/share/nginx/html;
    index index.html index.htm;

    ssl_certificate /etc/letsencrypt/live/intranet-knowledge.servehalflife.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/intranet-knowledge.servehalflife.com/privkey.pem;

    location / {
        proxy_pass http://localhost:3001;
    }
}

